### ISSUE TITLE
typo on https://apexmovement.tech/superglidetrainer/

### ISSUE THREAD

**Issue by mpl** [muckelba/superglidetrainer#3]
I didn't find the static text for the website in the repo (otherwise I would have opened a PR myself), but I didn't know where else to report that typo. Anyway:

s/harder then timing/harder than timing/

**Comment by muckelba** [comment]
Thanks for the heads up, I've just fixed it. You can also ping me in mokeys discord (if you use it, its linked at the footer) for such things :)

**Comment by mpl** [comment]
ah, good to know, thanks. I sometimes lurk on the r5reloaded discord but I've never joined mokey's. Maybe I should ;)
